name: Build And Deploy Code

on: [push, pull_request]

jobs: 
    job1:
        runs-on: ubuntu-latest
        steps: 
            - name: pulling git repo
              uses: actions/checkout@v4
            - name: say hello thabang
              run: echo "hello thabang mbhele, chief executive officer @ universe.inc"


             



          





